# Generated by Django 4.2.16 on 2025-05-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_heading_post_alter_postanalytics_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postanalytics',
            old_name='clicks_through_rate',
            new_name='click_through_rate',
        ),
    ]
